# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`

# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|

  s.name = "chrono_trigger"
  s.authors = ["Jon Ciccone"]
  s.date = "2013-01-10"
  s.summary = "Rails cron jobs."
  s.description = "This gem allows you to write, deploy, and maintain cron jobs withing the rails framework."
  s.email = "darful@gmail.com"
  s.homepage = "https://github.com/darful/chrono_trigger"
  s.version = '0.2.1'

  s.files = [
      ".project",
      "History.txt",
      "Manifest.txt",
      "PostInstall.txt",
      "README.rdoc",
      "Rakefile",
      "VERSION.yml",
      "bin/chrono_trigger",
      "chrono_trigger.gemspec",
      "lib/chrono_trigger.rb",
      "lib/chrono_trigger/cron_entry.rb",
      "lib/chrono_trigger/process.rb",
      "lib/chrono_trigger/runner.rb",
      "lib/chrono_trigger/shell.rb",
      "lib/chrono_trigger/tasks.rb",
      "lib/chrono_trigger/trigger.rb",
      "lib/chrono_trigger/version.rb",
      "lib/tasks/chrono_trigger.rake",
      "lib/triggers/test_triggers.rb",
      "script/console",
      "script/destroy",
      "script/generate",
      "test/test_chrono_trigger.rb",
      "test/test_cron_entry.rb",
      "test/test_helper.rb",
      "test/test_shell.rb",
      "test/test_trigger.rb",
      "test/triggers.rb"
  ]
  s.executables   = s.files.grep(%r{^bin/}).map{ |f| File.basename(f) }
  s.test_files    = s.files.grep(%r{^(test)/})
  s.require_paths = ["lib"]
  s.extra_rdoc_files = ["README.rdoc"]

  s.add_dependency "activesupport", ">= 2.3.4"
  #s.add_dependency "activerecord", ">= 2.3.4"

  s.add_development_dependency "shoulda", ">= 2.10"
  s.add_development_dependency "mocha", ">= 0.9.5"

  s.add_development_dependency "rubyforge"
  s.add_development_dependency "git"
  s.add_development_dependency "technicalpickles-jeweler"

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
