# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "chrono_trigger"
  s.version = "0.1.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jon Ciccone"]
  s.date = "2012-08-22"
  s.description = "TODO"
  s.email = "darful@gmail.com"
  s.executables = ["chrono_trigger"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
     "Manifest.txt",
     "PostInstall.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "bin/chrono_trigger",
     "chrono_trigger.gemspec",
     "lib/chrono_trigger.rb",
     "lib/chrono_trigger/cron_entry.rb",
     "lib/chrono_trigger/process.rb",
     "lib/chrono_trigger/runner.rb",
     "lib/chrono_trigger/shell.rb",
     "lib/chrono_trigger/tasks.rb",
     "lib/chrono_trigger/trigger.rb",
     "lib/tasks/chrono_trigger.rake",
     "lib/triggers/test_triggers.rb",
     "script/console",
     "script/destroy",
     "script/generate",
     "test/test_chrono_trigger.rb",
     "test/test_cron_entry.rb",
     "test/test_helper.rb",
     "test/test_shell.rb",
     "test/test_trigger.rb",
     "test/triggers.rb"
  ]
  s.homepage = ""
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "TODO"
  s.test_files = [
    "test/test_chrono_trigger.rb",
     "test/test_cron_entry.rb",
     "test/test_helper.rb",
     "test/test_shell.rb",
     "test/test_trigger.rb",
     "test/triggers.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
